import './globals.css'
import {Inter} from 'next/font/google'
import Provider from "@/components/provider";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Next Technologies Corp',
    description: 'Generated by create next app',
}

export default function RootLayout(props:any) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Provider>
            {props.children}
        </Provider>
        </body>
        </html>
    )
}
